/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IEventTicketForIncentives } from "./IEventTicketForIncentives";
export type { IPOAPAttendance } from "./IPOAPAttendance";
export type { IncentiveManager } from "./IncentiveManager";
