/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEventTicketForIncentives,
  IEventTicketForIncentivesInterface,
} from "../../../../contracts/modules/IncentiveManager.sol/IEventTicketForIncentives";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "eventId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSold",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IEventTicketForIncentives__factory {
  static readonly abi = _abi;
  static createInterface(): IEventTicketForIncentivesInterface {
    return new Interface(_abi) as IEventTicketForIncentivesInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEventTicketForIncentives {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IEventTicketForIncentives;
  }
}
