/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPOAPAttendance,
  IPOAPAttendanceInterface,
} from "../../../../contracts/modules/IncentiveManager.sol/IPOAPAttendance";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "owner",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPOAPAttendance__factory {
  static readonly abi = _abi;
  static createInterface(): IPOAPAttendanceInterface {
    return new Interface(_abi) as IPOAPAttendanceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPOAPAttendance {
    return new Contract(address, _abi, runner) as unknown as IPOAPAttendance;
  }
}
