/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as incentiveManagerSol from "./IncentiveManager.sol";
export type { incentiveManagerSol };
export type { POAPAttendance } from "./POAPAttendance";
