/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ipoapSol from "./IPOAP.sol";
export { IEventFactory__factory } from "./IEventFactory__factory";
export { IEventTicket__factory } from "./IEventTicket__factory";
export { IIncentiveManager__factory } from "./IIncentiveManager__factory";
